
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wilme
 */
public class F_ing_GUI extends javax.swing.JFrame {

    /**
     * Creates new form F_ing_GUI
     */
    public F_ing_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Universo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2CrearSer = new javax.swing.JButton();
        jButton1CrearUniverso = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldNombreUniverso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        CBuniversos = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton2ModifSer = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NombreModificar = new javax.swing.JTextField();
        IdModificar = new javax.swing.JTextField();
        PoderModificar = new javax.swing.JTextField();
        AñosModificar = new javax.swing.JTextField();
        RazaModificar = new javax.swing.JComboBox<>();
        jComboBoxModificarUniverso = new javax.swing.JComboBox<>();
        CambiarSerCB = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        CB_EliminarSer = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDbuscar = new javax.swing.JTextField();
        NombreBuscar = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCARGAR = new javax.swing.JMenuItem();
        jMenuItemGUARDAR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Universo.setText("Universo");
        jPanel1.add(Universo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 18, 60, 20));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jButton2CrearSer.setText("C r e a r");
        jButton2CrearSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CrearSerActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2CrearSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jButton1CrearUniverso.setText("C r e a r");
        jButton1CrearUniverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CrearUniversoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1CrearUniverso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 560, 20));
        jPanel1.add(jTextFieldNombreUniverso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 200, -1));

        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel6.setText("Poder");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel7.setText("Años");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel8.setText("Universo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLabel9.setText("Raza");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jLabel10.setText("Nombre");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 120, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 120, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 120, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Amanto" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 120, -1));

        CBuniversos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(CBuniversos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 120, -1));

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2ModifSer.setText("Modif");
        jButton2ModifSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ModifSerActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2ModifSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 560, 20));

        jLabel11.setText("ID");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel12.setText("Poder");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel13.setText("Años");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel14.setText("Universo");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jLabel15.setText("Raza");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jLabel16.setText("Nombre");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        jPanel2.add(NombreModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, -1));
        jPanel2.add(IdModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, -1));
        jPanel2.add(PoderModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, -1));
        jPanel2.add(AñosModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 120, -1));

        RazaModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Amanto" }));
        jPanel2.add(RazaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 120, -1));

        jComboBoxModificarUniverso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBoxModificarUniverso, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 120, -1));

        CambiarSerCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CambiarSerCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CambiarSerCBItemStateChanged(evt);
            }
        });
        jPanel2.add(CambiarSerCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, -1));

        jTabbedPane1.addTab("Modificar", jPanel2);

        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });
        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        CB_EliminarSer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(CB_EliminarSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 240, 30));

        jTabbedPane1.addTab("Eliminar", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Buscar Ser");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 60));

        jLabel2.setText("Nombre");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 60, -1));

        jLabel3.setText("ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        IDbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDbuscarActionPerformed(evt);
            }
        });
        jPanel4.add(IDbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 140, -1));
        jPanel4.add(NombreBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 140, -1));

        BotonBuscar.setText("Search");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        jPanel4.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jTabbedPane1.addTab("Buscar", jPanel4);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemCARGAR.setText("Guardar");
        jMenuItemCARGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCARGARActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCARGAR);

        jMenuItemGUARDAR.setText("Cargar");
        jMenuItemGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGUARDARActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemGUARDAR);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCARGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCARGARActionPerformed
        Escribirtodo();
    }//GEN-LAST:event_jMenuItemCARGARActionPerformed

    private void IDbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDbuscarActionPerformed

    private void jButton1CrearUniversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CrearUniversoActionPerformed
        Universos.add(new Universo(jTextFieldNombreUniverso.getText()));
        cargarComboboxUniversos();

        jTextFieldNombreUniverso.setText("");
    }//GEN-LAST:event_jButton1CrearUniversoActionPerformed

    private void jButton2CrearSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CrearSerActionPerformed
        if (Universos.size() == 0) {
            JOptionPane.showMessageDialog(this, "Primero crea un universo");
        } else {
            Seres.add(new SerViv(jTextField1.getText(),
                    Integer.parseInt(jTextField2.getText()),
                    Integer.parseInt(jTextField3.getText()),
                    Integer.parseInt(jTextField4.getText()),
                    (Universo) CBuniversos.getSelectedItem(),
                    (jComboBox1.getSelectedItem()).toString()));
            //System.out.println(Seres);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            cargarComboboxSeresEliminar();
        }

    }//GEN-LAST:event_jButton2CrearSerActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        cargarComboboxSer();

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_jPanel2ComponentShown

    private void CambiarSerCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CambiarSerCBItemStateChanged
        NombreModificar.setText(((SerViv) CambiarSerCB.getSelectedItem()).getNombre());
        IdModificar.setText("" + ((SerViv) CambiarSerCB.getSelectedItem()).getID());
        PoderModificar.setText("" + ((SerViv) CambiarSerCB.getSelectedItem()).getPoder());
        AñosModificar.setText("" + ((SerViv) CambiarSerCB.getSelectedItem()).getAños());
        cargarComboboxUniversoModis();


    }//GEN-LAST:event_CambiarSerCBItemStateChanged

    private void jButton2ModifSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ModifSerActionPerformed
        Seres.get(CambiarSerCB.getSelectedIndex()).setNombre(NombreModificar.getText());
        Seres.get(CambiarSerCB.getSelectedIndex()).setID(Integer.parseInt(IdModificar.getText()));
        Seres.get(CambiarSerCB.getSelectedIndex()).setPoder(Integer.parseInt(PoderModificar.getText()));
        Seres.get(CambiarSerCB.getSelectedIndex()).setAños(Integer.parseInt(AñosModificar.getText()));
        Seres.get(CambiarSerCB.getSelectedIndex()).setUniverso(((Universo) jComboBoxModificarUniverso.getSelectedItem()));
        Seres.get(CambiarSerCB.getSelectedIndex()).setRaza(RazaModificar.getSelectedItem().toString());

        cargarComboboxSeresEliminar();

    }//GEN-LAST:event_jButton2ModifSerActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        cargarComboboxSeresEliminar();
    }//GEN-LAST:event_jPanel3ComponentShown

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
        cargarComboboxSeresEliminar();
    }//GEN-LAST:event_jPanel3FocusGained

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        Seres.remove(CB_EliminarSer.getSelectedIndex());
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        for (SerViv Sere : Seres) {
            if (Sere.getID() == Integer.parseInt(IDbuscar.getText()) && Sere.getNombre().equals(NombreBuscar.getText())) {
                JOptionPane.showMessageDialog(this, "Este ser si existe");

            }
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        //leertodo();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGUARDARActionPerformed
        leertodo();
        cargarComboboxSeresEliminar();
        cargarComboboxSer();
        cargarComboboxUniversoModis();
        cargarComboboxUniversos();        
    }//GEN-LAST:event_jMenuItemGUARDARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_ing_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_ing_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_ing_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_ing_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_ing_GUI().setVisible(true);
            }
        });
    }

    private void cargarComboboxUniversos() {
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        CBuniversos.setModel(m);

        for (Universo univ : Universos) {
            m.addElement(univ);
            //System.out.println(pers.toString());
        }
        CBuniversos.setModel(m);
    }

    private void cargarComboboxUniversoModis() {
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        jComboBoxModificarUniverso.setModel(m);

        for (Universo univ : Universos) {
            m.addElement(univ);
            //System.out.println(pers.toString());
        }
        jComboBoxModificarUniverso.setModel(m);
    }

    private void cargarComboboxSer() {
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        CambiarSerCB.setModel(m);

        for (SerViv Ser : Seres) {
            m.addElement(Ser);
            //System.out.println(pers.toString());
        }
        CambiarSerCB.setModel(m);
    }

    private void cargarComboboxSeresEliminar() {
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        CB_EliminarSer.setModel(m);

        for (SerViv Ser : Seres) {
            m.addElement(Ser);
            //System.out.println(pers.toString());
        }
        CB_EliminarSer.setModel(m);
    }

    private void Escribirtodo() {

        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            for (SerViv Ser : Seres) {
                fw = new FileOutputStream("./Seres/" + Ser.getID());
                bw = new ObjectOutputStream(fw);
                bw.writeObject(Ser);

            }
            bw.flush();
        } catch (Exception ex) {
        } finally {
            try {
                bw.close();
                fw.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Oh no, algo salio mal");
            }
        }

        try {
            for (Universo univ : Universos) {
                fw = new FileOutputStream("./Universos/" + univ.getNombre());
                bw = new ObjectOutputStream(fw);
                bw.writeObject(univ);

            }
            bw.flush();
        } catch (Exception ex) {
        } finally {
            try {
                bw.close();
                fw.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Oh no, algo salio mal");
            }
        }

        try {
            for (Universo univ : Universos) {
                fw = new FileOutputStream("./Todo/" + univ.getNombre());
                bw = new ObjectOutputStream(fw);
                bw.writeObject(univ);

            }
            for (SerViv Ser : Seres) {
                fw = new FileOutputStream("./Todo/" + Ser.getID());
                bw = new ObjectOutputStream(fw);
                bw.writeObject(Ser);

            }
            bw.flush();
        } catch (Exception ex) {
        } finally {
            try {
                bw.close();
                fw.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Oh no, algo salio mal");
            }
        }

    }

    private void leertodo() {
        try {
            Universos = new ArrayList();
            Seres = new ArrayList();
            Universo uni;
            File archivo = new File("./Todo/");

            File[] arrayfile = archivo.listFiles();
            for (File file : arrayfile) {
                if (archivo.exists()) {
                    FileInputStream entrada
                            = new FileInputStream(file);
                    ObjectInputStream objeto
                            = new ObjectInputStream(entrada);
                    try {
                        Object coso = objeto.readObject();

                        if (coso instanceof Universo) {
                            Universos.add((Universo) coso);

                        } else {
                            Seres.add((SerViv) coso);
                        }
                    } catch (EOFException e) {
                        //encontro el final del archivo
                    }
                    objeto.close();
                    entrada.close();
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private ArrayList<Universo> Universos = new ArrayList();
    private ArrayList<SerViv> Seres = new ArrayList();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AñosModificar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JComboBox<String> CB_EliminarSer;
    private javax.swing.JComboBox<String> CBuniversos;
    private javax.swing.JComboBox<String> CambiarSerCB;
    private javax.swing.JTextField IDbuscar;
    private javax.swing.JTextField IdModificar;
    private javax.swing.JTextField NombreBuscar;
    private javax.swing.JTextField NombreModificar;
    private javax.swing.JTextField PoderModificar;
    private javax.swing.JComboBox<String> RazaModificar;
    private javax.swing.JLabel Universo;
    private javax.swing.JButton jButton1CrearUniverso;
    private javax.swing.JButton jButton2CrearSer;
    private javax.swing.JButton jButton2ModifSer;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxModificarUniverso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCARGAR;
    private javax.swing.JMenuItem jMenuItemGUARDAR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldNombreUniverso;
    // End of variables declaration//GEN-END:variables
}
